# Generated by Django 2.2.1 on 2019-05-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160)),
                ('date', models.CharField(max_length=30)),
                ('percent', models.IntegerField()),
            ],
        ),
    ]
